### ISSUE TITLE
[Profile Management][Edit Profile] Fix must display invalid phone number error upon leaving phone textbox.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#103]
### **Description:**
Must display invalid phone number error upon leaving phone textbox.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on edit profile screen

### **Steps to Reproduce:** 
1. Attach valid photo
2. Input valid username
3. Input valid name
4. Input valid surname
5. Input valid email address
6. input invalid mobile number format
7. Tap Update Profile button

### **Expected Result:** 
Display invalid mobile number format error message.

### **Actual Result:** 
Displaying invalid phone format error message after OTP verification instead of displaying the error first before proceeding with OTP Verification.

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157162974-a575f255-2d3d-47b1-b501-360677a78b3f.mp4
https://user-images.githubusercontent.com/100174697/157163008-afa24042-e208-4e1f-84ee-6aded20b62d1.mp4

**Comment by TaiTrien** [comment]
Hi @jkevincalado, the phone will not implement OTP for now. Please check again and move this ticket from this sprint

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
