### ISSUE TITLE
[Add Accounts] Fix must display accurate public address below username label on account list.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#104]
### **Description:**
Must display accurate public address below username label on account list.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Dashboard

### **Steps to Reproduce:** 
1. Tap Hamburger button
2. View drawer options
3. Tap account name

### **Expected Result:** 
Display add account screen with accurate details per account.

### **Actual Result:** 
Displaying 0x0 public address below Account label

### **Attachment/s:** 
![Screenshot_20220307-161523](https://user-images.githubusercontent.com/100174697/157163321-32f0c4f0-96ef-480b-ac77-b731a2c5d303.jpg)

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check it on the next version v1.0.18

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.18
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
