### ISSUE TITLE
[Account Maintenance][SEED Phrase Video] Fix must display Klubcoin Video regarding SEED Phrase Importance.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#106]
### **Description:**
Must display Klubcoin Video regarding SEED Phrase Importance.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Dashboard.
5. Secret Recovery Code already setup

### **Steps to Reproduce:** 
1. Tap Hamburger button
2. View drawer options
3. Tap Settings
4. Tap Security & Privacy
5. Tap SEED Phrase Video

### **Expected Result:** 
Display Klubcoin Video

### **Actual Result:** 
Displaying Metamask Video

### **Attachment/s:** 
![Screenshot_20220307-153655](https://user-images.githubusercontent.com/100174697/157164569-ab48916e-ec6b-419f-8f20-50551c9fe59a.jpg)

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, we have not had video for Klubcoin yet

**Comment by salonigoel24** [comment]
@TaiTrien 1.Show Coming Soon banner In place of video.
2. Change the header <test> to "Protect your wallet" as in metamask.

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`PASSED`"

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.18
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
