### ISSUE TITLE
[Wallet Management][Send Token] Fix must not display JSON RPC Error for Send Token Transactions

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#107]
### **Description:**
Must not display JSON RPC Error for Send Token Transactions

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.15
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on send token confirmation Screen.

### **Steps to Reproduce:** 
1. View send token confirmation details
2. Tap send button

### **Expected Result:** 
1. Display insufficient funds error message for insufficient token balance.
2. Display successfully sent token

### **Actual Result:** 
Displaying transaction error internal JSON-RPC Error

### **Attachment/s:** 
![Screenshot_20220307-173535](https://user-images.githubusercontent.com/100174697/157165752-5a766cbe-4945-4a74-853a-60bf8d337848.jpg)

**Comment by jcalado-freelancersph** [comment]
`v1.0.0.15` now also displays` JSON-RPC Error `even for sending transactions with sufficient balance.

FYR: @salonigoel24 @hanle9 

**Attachment/s:**
https://user-images.githubusercontent.com/100174697/158325961-a3b6ec50-85c2-434e-a237-0401ee84f077.mp4

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please change the network URL and test again

**Comment by jcalado-freelancersph** [comment]
Still displaying JSON-RPC error for valid transactions. Thou the genesis wallet is already getting deducted while the recipient account is not receiving the tokens.

![image](https://user-images.githubusercontent.com/100174697/158516590-4db5c088-15b4-4aaa-ba0c-765bc82399f5.png)
![image](https://user-images.githubusercontent.com/100174697/158516604-6049f653-dade-48d0-a06a-6c4e167b312e.png)
![image](https://user-images.githubusercontent.com/100174697/158516627-998a34f8-b839-48ae-b53e-53eda7a05df8.png)

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check again on the next version

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
