### ISSUE TITLE
[Wallet Management][Send Token][Gas Limit] Fix must not display stack trace errors for inputting alphabet, special, multiple decimal, negative value, more than maximum boundary value, spaces in between characters, leading spaces, trailing spaces, fractional, less than minimum boundary value inputs for Gas Limit Amount Textbox.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#108]
### **Description:**
Must display insufficient token balance instead of JSON RPC Error

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on send token confirmation screen.

### **Steps to Reproduce:** 
1. Tap Edit Network Fee link
2. Tap Gas Limit Textbox
3. Input alphabet characters
4. Input special characters
5. Input multiple decimal values
6. Input negative value
7. Input more than maximum boundary value
8. Input less than minimum boundary value
9. Input leading, in between, and trailing spaces value
10. Input Fractional values

### **Expected Result:** 
Display respective validation error handlers

### **Actual Result:** 
Displaying Stack trace errors, application is broken.

### **Attachment/s:** 
![Screenshot_20220307-164102](https://user-images.githubusercontent.com/100174697/157166944-8be0e986-a604-4834-a978-9f850b854b7a.jpg)
![Screenshot_20220307-164119](https://user-images.githubusercontent.com/100174697/157166965-27a7fe2f-9fb1-4817-aa94-40abb81cdf5c.jpg)
![Screenshot_20220307-172911](https://user-images.githubusercontent.com/100174697/157166986-efb1b79d-7a3b-4112-8d88-299675bea214.jpg)

**Comment by jcalado-freelancersph** [comment]
https://drive.google.com/file/d/1t8vIQEmdFQZmGHag3yE1OL_aljtoDQhF/view

FYR @hanle9 @TaiTrien @salonigoel24

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please check it on the next version v.1.0.17

**Comment by jcalado-freelancersph** [comment]
Reverification will happen on v1.0.0.17

FYR: @salonigoel24

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`PASSED`"
