### ISSUE TITLE
[Wallet Management][Receive Token] Fix should display masked URL, able to redirect to Klubcoin app, and have a handler on opening receive Token link through external wallet app upon accessing payment request link.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#109]
### **Description:**
Should display masked URL, able to redirect to Klubcoin app, and have a handler on opening receive Token link through external wallet app upon accessing payment request link.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen

### **Steps to Reproduce:** 
1. Tap Receive button
2. View public address
3. Tap request payment button
4. Select asset
5. Enter valid amount value
6. Tap Next
7. Tap Send button
8. Select external messaging app
9. Choose recipient
10. Open external messaging app used
11. Tap sent payment request link

### **Expected Result:** 
1.The url should be masked..shouldn't show account2.liquichain
2. If opened with Klubcoin app, send screen should open up with the address pre populated.
3.if opened with any other app than Klubcoin, it should be properly handled ..show some error message. 

### **Actual Result:** 
URL Not Masked
No redirection to Klubcoin App
No external app handler

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157174001-82579fa2-7e26-421c-b560-2a2a734563e3.mp4

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please check it on the next version v.1.0.17

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Re-Open`"

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check it. It's fixed already

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.19
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
