### ISSUE TITLE
[Onboarding Screens- Sprint2] 1 welcome screen is there when user has already created wallet.

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#11]
**Description:**
Once user has already created a wallet, only 1 welcome screen is visible next time user opens the app, with a "Go to My Wallet" button .

**Pre requisite:**
Klubcoin app is installed on user's device.
User has created the wallet.
Build Version: 1.0.2

**Steps to Reproduce:**

Once user has already created a wallet, only 1 welcome screen is visible next time user opens the app, with a "Go to My Wallet" button .

Actual Result:
User directly lands on login page.

**Comment by walterbernardo23** [comment]
**Fixed:**
1. After user created a wallet, 1 welcome screen is now showing the next time user opens the app, with a "Go to My Wallet" button.

Please see attached:
<img width="450" alt="11_Fixed" src="https://user-images.githubusercontent.com/98941970/154627565-99800e3c-174b-45c5-9b6a-049584884458.png">


Closing ticket.
