### ISSUE TITLE
[Wallet Management][Receive Token] Fix should not accept more than 256 character input on receive token amount textbox.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#114]
### **Description:**
Should not accept more than 256 character input on receive token amount textbox.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen

### **Steps to Reproduce:** 
1. Tap Receive button
2. View public address
3. Tap request payment button
4. Select asset
5. Enter more than maximum boundary numerical value

### **Expected Result:** 
Amount textbox should have maximum boundary value.

### **Actual Result:** 
Accepting more than 256 character input

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157175889-a3ff4015-6d92-443f-9be1-63a3b0f19b2c.mp4

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, firstly we don't check validation when the user is entering. We just check after the user clicks on next. Please check it and close this ticket

**Comment by jcalado-freelancersph** [comment]
@salonigoel24 , we can defer this issue for now and focus on breaking points.

FYR: @TaiTrien , yes we have validations on Backend while, it is recommended as standard to have a Frontend validation to minimize the API requests from the client side for better performance and UX.

Remarks: We don't need to flood the server with unwanted data requests specially we're having a lot of issue/s on our server (slow, unstable). These kind of data validations on text fields will greatly contribute in overall performance and stability of the application.

**Comment by TaiTrien** [comment]
Hi @jkevincalado, we just validate on Frontend without any API requests

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
