### ISSUE TITLE
[Wallet Management][Receive Token] Fix should not accept less than minimum boundary value input on receive token amount textbox.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#115]
### **Description:**
Should not accept less than minimum boundary value input on receive token amount textbox.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen

### **Steps to Reproduce:** 
1. Tap Receive button
2. View public address
3. Tap request payment button
4. Select asset
5. Enter less than minimum boundary numerical value

### **Expected Result:** 
Amount textbox should have minimum boundary value (up to 18 decimal places only).

### **Actual Result:** 
Accepting 0.0000000000000000000000000000000000000000001 input

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157176435-50da257a-e3df-4d9b-a69b-1a07225fefac.mp4

**Comment by TaiTrien** [comment]
HI @jkevincalado, please check on the next version v.1.0.7

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
