### ISSUE TITLE
[Wallet Management][Receive Token] Fix should not accept null value input on receive token amount textbox.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#117]
### **Description:**
Should not accept null value input on receive token amount textbox.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen

### **Steps to Reproduce:** 
1. Tap Receive button
2. View public address
3. Tap request payment button
4. Select asset
5. Input 0.00 amount value

### **Expected Result:** 
Next button should be disabled.

### **Actual Result:** 
Accepting 0.00 token request

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157177407-afecc10f-ab8b-4cf8-9b03-d208be562e44.mp4

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check it on the next version v.1.0.8

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.18
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
