### ISSUE TITLE
[Wallet Management][Receive Token] Fix should display masked generated URL on confirm receive token screen.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#118]
### **Description:**
Should display masked generated URL on confirm receive token screen.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen

### **Steps to Reproduce:** 
1. Tap Receive button
2. View public address
3. Tap request payment button
4. Select asset
5. Enter valid amount value
6. Tap Next
7. View generated link

### **Expected Result:** 
Display receive token amount address should be masked.

### **Actual Result:** 
Displaying unmasked generated URL

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157177743-f078fb36-7d31-443a-9ee2-239a3f65c839.mp4

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please check it on the next version v.1.0.17

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Re-Open`"

**Comment by TaiTrien** [comment]
HI @jkevincalado, could you please check it on v1.0.18 please ?

**Comment by jkevincalado** [comment]
Hi @TaiTrien , this is how it looks like now in v1.0.0.18 :)
![image](https://user-images.githubusercontent.com/100174697/159202492-4facf04c-595c-45d9-abb1-96129a8e4266.png)

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.19
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
