### ISSUE TITLE
[Wallet Management][Receive Token] Fix should not display truncated receive token amount value when preceeding request is invalid.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#119]
### **Description:**
Should not display truncated receive token amount value when preceding request is invalid.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen
5. User entered an invalid token amount

### **Steps to Reproduce:** 
1. Tap Receive button
2. View public address
3. Tap request payment button
4. Select asset
6. Enter valid amount value
7. Tap Next
8. View Total Token Amount

### **Expected Result:** 
Display accurate total amount of tokens to receive.

### **Actual Result:** 
Displaying truncated value when preceding request is invalid.

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157178207-16ad61d2-9aa6-44fc-a633-cee75b42a8a3.mp4

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check it on v.1.0.17. I have fixed it already

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
