### ISSUE TITLE
[Wallet Management][Send Token via QR Code] Fix must not display truncated token amount if payment request is up to 18 decimal value after scanning a valid payment request QR Code.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#121]
### **Description:**
Must not display truncated token amount if payment request is up to 18 decimal value after scanning a valid payment request QR Code.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen.
5. QR Code value should be 0.000000000000000001

### **Steps to Reproduce:** 
1. Tap Send button
2. View send tokens screen
3. Tap QR Code button
4. Scan correct QR Code

### **Expected Result:** 
Proceed to send token amount screen.

### **Actual Result:** 
Displaying truncated value for 18 decimal token request.

### **Attachment/s:** 
https://drive.google.com/file/d/1F5UOXPxuNSGzsc-ZPUCQGCiTHmXvcX6e/view

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check on the next version v1.0.7

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`PASSED`"
