### ISSUE TITLE
[Wallet Management][Send Token Confirmation] Fix should not display small white boxes on total amount, amount, network fee values when application is fetching the data.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#124]
### **Description:**
Should not display small white boxes on total amount, amount, network fee values when application is fetching the data.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen.

### **Steps to Reproduce:** 
1. Tap Send button
2. View send tokens screen
3. Tap QR Code button
4. Scan correct QR Code
5. Input valid amount
6. Tap next button

### **Expected Result:** 
Display send token confirmation screen.

### **Actual Result:** 
Displaying small white boxes on total amount, amount, network fee values when application is fetching the data.

### **Attachment/s:** 
https://drive.google.com/file/d/1F5UOXPxuNSGzsc-ZPUCQGCiTHmXvcX6e/view

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check on the next version v1.0.

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`PASSED`"
