### ISSUE TITLE
[Wallet Management][Send Token] Fix must not let user proceed to send amount screen if account has 0 token balance. (Next button disabled for Senders with 0 Token Balance))

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#125]
### **Description:**
Must not let user proceed to send amount screen if account has 0 token balance.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen.

### **Steps to Reproduce:** 
1. Tap Send button
2. View send tokens screen
3. Select sender with 0 Token Balance
4. Select correct recipient
5. Tap Next

### **Expected Result:** 
Disable next button if selected sender has 0 token balance

### **Actual Result:** 
Being able to proceed to send amount screen even if account has 0 token balance.

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157185698-92b63420-2039-4ed6-ad8b-a6b81ae050ea.mp4

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check on the next version v.1.0.7

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check on the v.1.0.8 version

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.18
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
