### ISSUE TITLE
[Wallet Management][Send Token] Fix must not lag or glitch upon tapping "Use Max" option for having up to 18 decimal token value.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#126]
### **Description:**
Must not lag or glitch upon tapping "Use Max" option for having up to 18 decimal token value.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen.

### **Steps to Reproduce:** 
1. Tap Send button
2. View send tokens screen
3. Tap QR Code button
4. Scan correct QR Code
5. Tap Use Max option

### **Expected Result:** 
Display accurate token amount.

### **Actual Result:** 
Tapping Use Max is laggy when account has long form of token value amount.

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157185719-f3e0a540-013e-4617-ba14-ac7a1d517fb2.mp4

**Comment by TaiTrien** [comment]
Hi @jkevincalado, the reason is the app needs to fetch the data at the entry point. Please close this ticket

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`PASSED`"
