### ISSUE TITLE
[Wallet Setup Sprint2] Create Wallet Screen - Phone number field is missing country code and correct format validation 

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#13]
**Description:**
Cell number should have valid format. Format accepted is +CCC-NNNNNNNNNN, where +CCC is max 3-digit country code preceded by a +, and NNNNNNNNNN 10 digit cell phone number. Any entry that does not translate to this definition will show validation message to user.

User should receive a sms on this number to verify.

**Pre requisite:**
Klubcoin app is installed on user’s device
User has clicked Create a New Wallet button.
Build Version: 1.0.2

**Steps to Reproduce:**
On Profile screen, click on phone number field.
**Expected Result:**

- Phone number field should accept +sign followed by country code.
- 10 digit phone number

**Actual Result:**
No option of entering + sign for country code

**Comment by walterbernardo23** [comment]
Phone field is now requiring country country. However, found the following issues:

1. Phone field allows 8-15 digit number after country code.
Expected: It should only allow 10 digit number after country code.
<img width="981" alt="8 to 15 digit phone number" src="https://user-images.githubusercontent.com/98941970/153995380-64f7905a-a2c2-4dcc-bc8c-b3bd3b8f6742.png">



2. Phone field allows space.
Expected: Only numbers should be allowed.
<img width="435" alt="phone number space" src="https://user-images.githubusercontent.com/98941970/153995402-f8534749-5b8f-4abf-826e-6707f3060195.png">

**Comment by walterbernardo23** [comment]
**Issue:**
1. Phone number field only accepts 10 digits. Error message display when less than or more than 10 digits.
<img width="418" alt="13_Fixed" src="https://user-images.githubusercontent.com/98941970/154617865-bbbcee71-999c-48e8-ad5e-1e524638f557.png">


**Issue:**
1. Phone field still accepts space.
<img width="474" alt="13_Reopen" src="https://user-images.githubusercontent.com/98941970/154617882-80be7509-33e6-4ea9-9c87-f38157d7919e.png">


2.

**Comment by walterbernardo23** [comment]
Closing this ticket.

Please track the existing issue on the ticket below:
* [ ] https://github.com/klubcoin/lcn-mobile/issues/24
