### ISSUE TITLE
[Wallet Management][Send Token] Fix should less than minimum boundary value input on send token amount textbox.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#132]
### **Description:**
Should less than minimum boundary value input on send token amount textbox.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen.

### **Steps to Reproduce:** 
1. Tap Send button
2. View send tokens screen
3. Tap QR Code button
4. Scan correct QR Code
5. Input less than minimum boundary value

### **Expected Result:** 
Amount textbox should have minimum boundary value. (Amount should be up to 18 decimal places only)

### **Actual Result:** 
Accepting 0.000000000000000000000000000000000000000000

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157188480-e81abb75-bf94-43c0-83e6-234d5462150f.mp4

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check it on the next version

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`PASSED`" with minor enhancement on the handler message.
Display:
"Token amount should be up to 18 decimal places only."

FYR: @salonigoel24 @hanle9 @TaiTrien
