### ISSUE TITLE
[Wallet Management][Send Token] Fix should not fractional value input on send token amount textbox.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#133]
### **Description:**
Should not fractional value input on send token amount textbox.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen.

### **Steps to Reproduce:** 
1. Tap Send button
2. View send tokens screen
3. Tap QR Code button
4. Scan correct QR Code
5. Input fractional numerical value

### **Expected Result:** 
Amount textbox should not accept fractional values.

### **Actual Result:** 
Accepting fractional input

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157189882-a3df3d47-2fd7-4d44-b3c3-0aae9cfeb6cb.mp4

**Comment by TaiTrien** [comment]
Hi @jkevincalado, we just validate after users press "Next" button not every time users entering. Please check again and close this ticket
![simulator_screenshot_A4BACCEB-FC2C-46D9-AB2A-8FBBB039471F](https://user-images.githubusercontent.com/32502320/158548384-05856535-ce97-41bb-b819-df96db975660.png)

**Comment by jkevincalado** [comment]
@salonigoel24 , we can defer this issue for now and focus on breaking points.

FYR: @TaiTrien , yes we have validations on Backend while, it is recommended as standard to have a Frontend validation to minimize the API requests from the client side for better performance and UX.

Remarks: We don't need to flood the server with unwanted data requests specially we're having a lot of issue/s on our server (slow, unstable). These kind of data validations on text fields will greatly contribute in overall performance and stability of the application.

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
