### ISSUE TITLE
[Wallet Management][Send Token] Fix should not accept null value input on send token amount textbox.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#134]
### **Description:**
Should not accept null value input on send token amount textbox.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen.

### **Steps to Reproduce:** 
1. Tap Send button
2. View send tokens screen
3. Tap QR Code button
4. Scan correct QR Code
5. Leave amount empty

### **Expected Result:** 
Proceed to confirmation button should be disabled.

### **Actual Result:** 
Accepting 0.00 send token amount

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157190055-546463f2-2214-46e2-8974-613f98990cae.mp4

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check on the next version v1.0.7

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`PASSED`"
