### ISSUE TITLE
[Wallet Management][Send Token Confirmation] Fix should not display truncated value for sending up to 18 decimal token amount value.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#135]
### **Description:**
Should not display truncated value for sending up to 18 decimal token amount value.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Wallet Screen.

### **Steps to Reproduce:** 
1. Tap Send button
2. View send tokens screen
3. Tap QR Code button
4. Scan correct QR Code
5. Input 0.000000000000000001 amount
6. Tap next button
7. View send token confirmation screen

### **Expected Result:** 
Display send token confirmation details accurately.

### **Actual Result:** 
Displaying truncated value for sending up to 18 decimal token amount value

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157190617-b9548132-cc7d-4901-93a4-c00b4e6a4424.mp4

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check on the next version v1.0.7

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`PASSED`"
