### ISSUE TITLE
[Wallet Management][Send Token][GWEI] Fix should not accept more than 256 character input on GWEI textbox.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#136]
### **Description:**
Should not accept more than 256 character input on GWEI textbox.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on send token confirmation screen.

### **Steps to Reproduce:** 
1. Tap Edit Network Fee link
2. Tap Gas Price Textbox
3. Input more than maximum boundary value amount
4. Tap save button

### **Expected Result:** 
Amount should have maximum boundary value

### **Actual Result:** 
Accepting more than 256 character input

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157190617-b9548132-cc7d-4901-93a4-c00b4e6a4424.mp4

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check on the next version v.1.0.17

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`PASSED`"

**Comment by salonigoel24** [comment]
Closing this since edit network fee is fixed with no edit option
