### ISSUE TITLE
[Wallet Management][Send Token] Fix should not be able to select same account as sender as recipient of token.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#137]
### **Description:**
Should not accept more than 256 character input on GWEI textbox.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Dashboard.

### **Steps to Reproduce:** 
1. Tap Hamburger button
2. View drawer options
3. Tap Send button
4. Tap transfer between my accounts options
5. Select account same with sender details

### **Expected Result:** 
Display can't select sender as recipient error message.

### **Actual Result:** 
Able to proceed send token to same account from sender.

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157194267-f199c7b2-730a-48ad-9b7a-b9acafe4f06a.mp4

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check on the next version v.1.0.17

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`PASSED`"
