### ISSUE TITLE
[Account Maintenance][Add Network] Fix should have URL validation handler for Block Explorer URL field.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#139]
### **Description:**
Should have URL validation handler for Block Explorer URL field.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on List of Network Screen.

### **Steps to Reproduce:** 
1. Tap Hamburger button
2. View drawer options
3. Tap Settings
4. Tap Network option
5. Enter invalid Block Explorer URL
6. Enter valid details on other fields.
7. Tap Add button

### **Expected Result:** 
Display unrecognized Block Explorer URL error message.

### **Actual Result:** 
Must have URL validation handler

### **Attachment/s:** 
![Screenshot_20220308-160631](https://user-images.githubusercontent.com/100174697/157194909-e6c4350f-ef04-4b3d-9021-fa053f63d0dc.jpg)

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.3
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
