### ISSUE TITLE
[Wallet Setup] Learn More link do not direct to Details Page, it redirects to Klubcoin Support Page with no details 

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#14]
**Description:**
Learn More link do not direct to Details Page, it redirects to Klubcoin Support Page with no details.

**Pre requisite:**
User has clicked Create a New Wallet button.
User completed Profile screen.
Build Version: 1.0.2

**Steps to Reproduce:**

On Password recovery conditions, click Learn more link.
Click Ok button.
Expected Result:
Learn More “link on Password recovery conditions opens the details page.

**Actual Result:**
Learn More link do not direct to Details Page, it redirects to Klubcoin Support Page with no details

**Attachment/s:**
<img width="199" alt="LearnMore_PasswordSetup_error" src="https://user-images.githubusercontent.com/98397235/153193679-ed38e732-0fd4-4bc2-b1b4-80c8d8b8ca92.png">

**Comment by salonigoel24** [comment]
Create a new repo on github and expose it as github pages. Keep dummy data as of now,. We will update the data once send by Stephane

**Comment by TaiTrien** [comment]
Hi @salonigoel24 @johncalado-manaty, please check and close this ticket

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.14
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`" This issue is now ready to be deployed on Production.
