### ISSUE TITLE
[Wallet Management][Buy Token] Fix should not display Transak Screen on list of purchase methods.

### ISSUE THREAD

**Issue by jcalado-freelancersph** [klubcoin/lcn-mobile#146]
### **Description:**
Should not display Transak Screen on list of purchase methods.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Dashboard

### **Steps to Reproduce:** 
1. Tap Hamburger button
2. View drawer options
3. Tap Buy button
4. Go back to previous screen

### **Expected Result:** 
Display previous screen.

### **Actual Result:** 
Displaying Transak Screen.

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/157376288-c3198a15-4fce-4565-bdf6-53a1bc199bde.mp4

**Comment by hanle9** [comment]
Current, press Buy button will navigate to coming soon screen

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Dev Environment
**Affects Version:** 1.0.0.13
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
![Screenshot_20220310-231352](https://user-images.githubusercontent.com/100174697/157794011-afa19686-5f78-4595-8fe9-1acf2bdeff78.jpg)

Remarks: Will transition this issue to "QA Done". **This issue is now ready to be deployed to Staging Environment.**

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.14
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`" This issue is now ready to be deployed on Production.
