### ISSUE TITLE
[Wallet Setup] Tutorial - Tutorial slider is not working

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#15]
**Description:**
Tutorial slider is not working

**Pre requisite:**
User has successfully created the wallet.
Build Version: 1.0.2

**Steps to Reproduce:**
Click "Done" button.
Click "Take the tour" button.
Check the tutorial and slide to the left and right.

**Expected Result:**
Tutorial slider should be working.

**Actual Result:**
Tutorial slider is not working.

**Attachment/s:**
<img width="198" alt="TutorialSlider" src="https://user-images.githubusercontent.com/98397235/153196633-28ebf629-ed57-491b-8486-148d5ece36cd.png">

**Comment by TaiTrien** [comment]
Hi @salonigoel24, as Han said that we disable it because it's not in design. If you still need it, please inform us the content of tutorial

**Comment by salonigoel24** [comment]
Closing, as tutorial not in design
