### ISSUE TITLE
[Profile Management][Imported Wallet] Fix must not display +undefined for empty mobile number for imported wallet.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#152]
### **Description:**
Must display mobile number for imported wallet.

**Build Environment:** Development Environment
**Affects Version:** 1.0.0.13
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has imported a wallet account
3. User already logged in
4. User is currently on Klubcoin Dashboard

### **Steps to Reproduce:** 
1. Tap Hamburger button
2. View drawer options
3. Tap photo thumbnail / gear icon
4. View account details

### **Expected Result:** 
Display empty country code if wallet has no saved phone number

### **Actual Result:** 
Displaying +undefined on country code

### **Attachment/s:** 
![Screenshot_20220310-230636](https://user-images.githubusercontent.com/100174697/157791100-f068a474-8166-409f-b5bf-2f6bc77fcbe1.jpg)

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.15
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

**Test Evidence:**
![image](https://user-images.githubusercontent.com/100174697/158321741-6d768245-9fd6-4a0e-a51a-5b89b2ec7ede.png)

Remarks: Will transition this issue to "`Re-Open`"

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.18
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Re-Open`" 

**Attachment:**
![image](https://user-images.githubusercontent.com/100174697/158924337-63704990-481c-4f5f-afb6-633ff05fe614.png)

**Comment by hanle9** [comment]
It will avail in version 1.0.0+19

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.19
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
