### ISSUE TITLE
Need to implement frontend validation hints for seamless user experience, smooth performance, and to minimize unnecessary backend API calls due to dummy data requests.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#155]
### **Importance**
- Validating the data on the client(Frontend) improves performance (fewer server calls) and improves user experience (faster validation messages). It’s pretty straight forward, it is done for the convenience of the user, showing them that the email field is mandatory, phone number has to follow a certain format, whatever it is. It also reduces the risk of the platform displaying stack trace errors or UI errors.

- Server side(Backend) validation is a double check "sanitization" and helps improve security. Here you can protect your system from improper data (ie ensuring data is encoded properly and protecting from script injections).

**Remarks:** That's why it's always recommended and best practice to always validate in both places. The simple rule is to never trust data from the user.

### **Scope:**
- **Wallet Creation**
- [x] 1. Name (Required: Continue button should be disabled if empty and displays hint/inline message.)
- [x] 2. Surname (Required: Continue button should be disabled if empty and displays hint/inline message.)
- [x] 3. Email Address (Required: Continue button should be disabled if empty and displays hint/inline message.
- [x] 4. Email Address valid format: Should follow Email Address Regex Format and and displays hint/inline message.
- [x] 5. Email Address uniqueness: Should not be the same with used Email address and displays hint/inline message)
- [x] 6. Username (Required: Continue button should be disabled if empty and displays hint/inline message
- [x] 7. Username Uniqueness: Should not be the same with used Email address and displays hint/inline message)

- **Profile**
- [x] 1. Name (Required: Update Profile button should be disabled if empty and displays hint/inline message.)
- [x] 2. Surname (Required: Update Profile button should be disabled if empty and displays hint/inline message.)
- [x] 3.  Mobile Number Valid Format: Should follow Mobile Number Regex Format and displays hint/inline message)

- **Send Token**
- [x] 1. Amount Text field must not accept alphabet character
- [x] 2. Amount Text field must not accept special "except 1 decimal"
- [x] 3. Amount Text field must not accept space characters. 
- [x] 4. Amount Text field should display hint/inline message validations for empty value.
- [x] 5. Amount Text field should display hint/inline message validations for less than minimum boundary value (If value entered has 19 decimal value display inline message/hint :"Amount allowed is only up to 18 decimals.")
- [x] 6. Amount Text field should not accept more than 256 character input
- [x] 7. Amount Text field should display hint/inline message validations for null value (0.00...) input.
- [x] 8. Next Button should be disabled for invalid amount value

- **Receive Token**
- [x] 1. Amount Text field must not accept alphabet character
- [x] 2. Amount Text field must not accept special "except 1 decimal"
- [x] 3. Amount Text field must not accept space characters. 
- [x] 4. Amount Text field should display hint/inline message validations for empty value.
- [x] 5. Amount Text field should display hint/inline message validations for less than minimum boundary value (If value entered has 19 decimal value display inline message/hint :"Amount allowed is only up to 18 decimals.")
- [x] 6. Amount Text field should not accept more than 256 character input
- [x] 7. Amount Text field should display hint/inline message validations for null value (0.00...) input.
- [x] 8. Next Button should be disabled for invalid amount value

- **Buy Token**
- [x] 1. Verify must not accept alphabet character input of user on amount to pay text field.	
- [x] 2. Verify must not accept special character input of user on amount to pay text field.
- [x] 3, Verify must not accept multiple decimal character input of user on on amount to pay text field.
- [x] 4. Verify must not accept negative numerical value input of user on amount to pay text field.
- [x] 5. Verify must not accept more than boundary value input of user on amount to pay text field. ($100,000 , €100,000) (up to 256 characters input only)
- [x] 6. Verify must display inline message / hint upon entering more than boundary value ("Cannot enter more than $100,000." , "Cannot enter more than €90,000.")
- [x] 7. Verify must not accept less than minimum value input of user on amount to pay text field. ($30, €20)
- [x] 8. Verify must display inline message / hint upon entering less than boundary value ("Cannot enter less than $30." , "Cannot enter less than €20.")
- [x] 9. Verify not accept space character input of user on amount to pay text field.
- [x] 10. Verify must not accept leading space before numerical value input of user on amount to pay text field.
- [x] 11. Verify must not accept trailing space after numerical value input of user on amount to pay text field.
- [x] 12. Verify must not accept fractional value input of user on amount to pay text field.
- [x] 13. Verify must not accept empty value input of user on amount to pay text field.
- [x] 14. Verify must not accept 0 pay amount value to be purchased on Buy KLUBs via PayPal.
- [x] 15. Verify must not accept more than 2 decimal digits entered by user on amount to pay text field.

- **New Email Address via Change Email**
- [x] 1. Email Address valid format: Should follow Email Address Regex Format and and displays hint/inline message.
- [x] 2. Email Address uniqueness: Should not be the same with already used Email address by other wallet accounts and displays hint/inline message)

- **Send Tips**
- [x] 1. Amount Text field must not accept alphabet character
- [x] 2. Amount Text field must not accept special "except 1 decimal"
- [x] 3. Amount Text field must not accept space characters. 
- [x] 4. Amount Text field should display hint/inline message validations for empty value.
- [x] 5. Amount Text field should display hint/inline message validations for less than minimum boundary value (If value entered has 19 decimal value display inline message/hint :"Amount allowed is only up to 18 decimals.")
- [x] 6. Amount Text field should not accept more than 256 character input
- [x] 7. Amount Text field should display hint/inline message validations for null value (0.00...) input.
- [x] 8. Next Button should be disabled for invalid amount value

- **Receive Tips**
- [x] 1. Amount Text field must not accept alphabet character
- [x] 2. Amount Text field must not accept special "except 1 decimal"
- [x] 3. Amount Text field must not accept space characters. 
- [x] 4. Amount Text field should display hint/inline message validations for empty value.
- [x] 5. Amount Text field should display hint/inline message validations for less than minimum boundary value (If value entered has 19 decimal value display inline message/hint :"Amount allowed is only up to 18 decimals.")
- [x] 6. Amount Text field should not accept more than 256 character input
- [x] 7. Amount Text field should display hint/inline message validations for null value (0.00...) input.
- [x] 8. Next Button should be disabled for invalid amount value

### **Related Issue/s:**
- [x] https://github.com/klubcoin/lcn-mobile/issues/128
- [x] https://github.com/klubcoin/lcn-mobile/issues/129
- [x] https://github.com/klubcoin/lcn-mobile/issues/130
- [x] https://github.com/klubcoin/lcn-mobile/issues/131
- [x] https://github.com/klubcoin/lcn-mobile/issues/133

**Comment by hanle9** [comment]
Wallet Creation, Profile, Send Token, Receive Token, New Email Address via Change Email are done. Please check it in next 
staging build.

**Comment by johncalado** [comment]
Hi @hanle9 

Minor adjustment with regards to Phone Number on Update Profile. Please see video clip below:
https://user-images.githubusercontent.com/100281200/165006508-769e935c-cee5-4cbe-af7b-49451d70fec3.mp4

Also on change email via Security & Privacy Setting. Please let app accept email address entered by user that is the same used on current wallet account.

**Comment by johncalado** [comment]
Closing this issue now as all checklist are properly implemented across the mobile application validation and text data handlers.
