### ISSUE TITLE
[Documentation links]Need webpages to show help documentation

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#156]
Currently the links on the app point to docs,liquichain.io - URL or a page not found
Need to have a webpage with correct information to displayed for following places: 

1. Wallet Setup>Terms and Conditions
2. Password Setup >Learn more
3. Secure Your Wallet > Why is it important? > Learn More Link
4. Drawer> Help
5. Drawer>About Klubcoin > Privacy Policy
6. Drawer>About Klubcoin >Terms of use
7. Drawer>About Klubcoin >Attributions
8. Drawer>About Klubcoin >View our support center
9. Drawer>About Klubcoin >Contact us
10. Onboarding > Import Wallet > Terms & Conditions

**Comment by dragons3232** [comment]
Hi @salonigoel24 , we need URLs for terms of use and privacy policy on klubcoin.net. Current URLs are not working. Those should be provided on main klubcoin portal instead of meveo

**Comment by jkevincalado** [comment]
### **Retested and verified on:**
**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.18
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

**Failing Criteria:**
Wallet Setup > Terms and Conditions
Password Setup >Learn more
Secure Your Wallet > Why is it important? > Learn More Link
Drawer> Help
Drawer>About Klubcoin > Privacy Policy
Drawer>About Klubcoin >Terms of use
Drawer>About Klubcoin >View our support center

**Passed Criteria:**
Drawer>About Klubcoin >Attributions
Drawer>About Klubcoin >Visit our Website
Drawer>About Klubcoin >Contact us
Onboarding > Import Wallet > Terms & Conditions

Remarks: Web Pages are very slow

cc: @salonigoel24

**Comment by salonigoel24** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/SALONI~1.GOE/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/SALONI~1.GOE/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



1 | KlubCoin - Terms Conditions.doc | 1. Wallet Setup>Terms and   Conditions       6. Drawer>About Klubcoin >Terms of use      7. Onboarding > Import Wallet > Terms & Conditions
-- | -- | --
2 | KlubCoin - Privacy _ Cookie Policy - GDPR - vGac v01 (1).doc | 5. Drawer>About Klubcoin > Privacy Policy
3 | KlubCoin - Password Setup.doc | 2. Password Setup >Learn more
4 | KlubCoin - Secure your wallet.doc | 3. Secure Your Wallet > Why is it important? > Learn More Link
5 | To reach our support team please email us at support@klubcoin.net | 8.Drawer>About Klubcoin >View our support center
6 | Menu Page?? Or KlubCoin - Terms Conditions.doc | 4.Drawer> Help



</body>

</html>

**Comment by salonigoel24** [comment]
Privacy policy needs to added for link on this page too
![image](https://user-images.githubusercontent.com/98397235/159197846-62be7fe3-83c7-4aaa-a562-c596e4d6a270.png)

**Comment by salonigoel24** [comment]
![1647920689540](https://user-images.githubusercontent.com/98397235/159403823-88490aa4-aa39-4f51-8178-7a2ec4f5bedb.JPEG)
Point Learn More link >KlubCoin - Secure your wallet.doc

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.20
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
