### ISSUE TITLE
[Login] Sign in with biometric not working as expected

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#16]
**Description:**
Sign In with biometric option not is very flickering,
1. Not  able to sign in using biometric if I logout from app.
2. Not able to  sign in using biometric if user navigates to some other app, and comes back to Klubcoin again and Remember me= False. Biometric page keeps on re-loading, and not letting to sign-In
3. It works when you close the app and opens again

**Pre requisite:**
Klubcoin app is installed on user’s device.
Build Version: 1.0.2

**Steps to Reproduce:**
**When Biometric is NOT working:**
**First Scenario**
Launch the Klubcoin App.
Login once with email password, and biometric option set to true, remember me= False
Navigate to some other app, and comes back to Klubcoin again 
Biometric page keeps on re-loading, and not letting to sign-In

**2nd Scenario**
Launch the Klubcoin App.
Login once with email password, and biometric option set to true
Logout 
Try  Signing in with biometric

**When Biometric is working:**
Launch the Klubcoin App.
Login once with email password, and biometric option set to true, remember me= "False"
Close the App, and open again.
Try with biometric, signup is successful and it opens dashboard.

Expected Result:
Biometric login should work in all times.

Actual Result:
Sign In with biometric option not is very flickering,

**Comment by walterbernardo23** [comment]
**Fixed:**
Biometrics is now showing and working properly after I exit the app and logout on the app. Biometrics options are also available on the login page beside email and password fields.

**Please see attached:**

https://user-images.githubusercontent.com/98941970/155068602-3b8516ba-843a-4845-8f4d-3fd7fc5725aa.mp4


https://user-images.githubusercontent.com/98941970/155068639-f3b02f93-58d0-4779-b24b-7eee60688de4.mp4

Closing ticket.
