### ISSUE TITLE
[Account Maintenance][Wallet Creation][Email Verification] Resend OTP Counter is being reset when user re-enters the OTP Verification Screen (Counter must be from OTP Configuration)

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#164]
### **Description:**
Resend OTP Counter is being reset when user re-enters the OTP Verification Screen (Counter must be from OTP Configuration)

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.14
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User is at Verify Email Screen at Wallet Creation Flow

### **Steps to Reproduce:** 
1. Tap Verify now
2. View Resend OTP Counter
3. Tap Back
4. Tap Verify now
5. View Resend OTP Counter

### **Expected Result:** 
Display original Resend OTP Counter

### **Actual Result:** 
Resend OTP Counter got reset

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/158312349-fc7715b3-e377-49bc-b23b-cbcd0f1b4ed0.mp4

**Comment by jkevincalado** [comment]
As per discussion, the fix for this issue is not feasible based on the current implementation for OTP Flows. We'll be moving this issue to Q2 for further discussion and alignment from Frontend and Backend Perspective.

I will transition this issue to "`DEFERRED`" and will be prioritized on the next development phase.

FYR: @hanle9 @salonigoel24

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Re-Open`"

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
