### ISSUE TITLE
[Account Maintenance][Wallet Creation][Email Verification] Exceeding OTP Attempts can be bypassed by re-entering the OTP Verification Screen (Must block OTP Request and attempt from OTP Configuration)

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#165]
### **Description:**
Exceeding OTP Attempts can be bypassed by re-entering the OTP Verification Screen (Must block OTP Request and attempt from OTP Configuration)

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.14
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. User is currently on Wallet Creation Flow
2. User is currently on Verify Email via Security & Privacy Flow
3. User is currently on Change Email via Security & Privacy Flow

### **Steps to Reproduce:** 
1. Tap Verify now
2. View Resend OTP Counter
3. Submit Incorrect OTP Code 5x
4. Tap Proceed to Dashboard / Security & Privacy button
5. Tap Verify now
6. Submit OTP Codes

Alternate Course:
1. Tap Change Email
2. Enter correct password
3. Input new email address
4. View Email Verification Screen
5. View Resend OTP Counter
6. Submit Incorrect OTP Code 5x
7. Tap Proceed to Security & Privacy button
8. Repeat Steps 1,2,3,4,5,6,7

### **Expected Result:** 
Should not be able to request and submit OTP Codes

### **Actual Result:** 
Allowing user to bypass maximum failed OTP attempt

### **Attachment/s:** 
https://drive.google.com/file/d/1EolhtPmzhkjQxjmgggMfq-Zpqdpspl4K/view

**Comment by jkevincalado** [comment]
As per discussion, the fix for this issue is not feasible based on the current implementation for OTP Flows. We'll be moving this issue to Q2 for further discussion and alignment from Frontend and Backend Perspective.

I will transition this issue to "`DEFERRED`" and will be prioritized on the next development phase.

FYR: @hanle9 @salonigoel24

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Re-Open`"

**Comment by johncalado** [comment]
Current Behaviour of mobile app:
 If user entered incorrect OTP codes up to 6 times then returned to the email verification screen user can still enter OTP Codes and attempt to verify my email address. It must not let user enter OTP codes anymore.

The change that happens now is when user try to resend an OTP code if already reached 6 failed attempts. It is displaying "You exceeded maximum of send OTP. Up to 6 sends per hour. Please try again." error message.

![image](https://user-images.githubusercontent.com/100281200/162158279-7487383f-9517-4877-86d8-c9171ea541d5.png)
![image](https://user-images.githubusercontent.com/100281200/162158304-b901ff1d-a634-488e-b1c3-d0df42dbafce.png)

Ideal is not to let user enter OTP Codes and Request new OTP Codes upon re-entering Email Verification Screen while blocked within 2 hours and will only display this message on Frontend: 
![image](https://user-images.githubusercontent.com/100281200/162158602-0b8c0ec0-662c-43a7-b7f1-94a0b8efe820.png)

Also, will be better if we can let user know how much time he still has to wait to be able to attempt again. Like 2 hours countdown HH:MM:SS. Thou I'm not sure if this will be easy to implement and reflect on mobile app.

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`" 

Revisions will be handled via formulating proper requirements specifications.
