### ISSUE TITLE
[Account Maintenance][Wallet Creation][Email Verification] Display Incorrect OTP instead of Incorrect OPT for incorrect OTP attempt.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#166]
### **Description:**
Display Incorrect OTP instead of Incorrect OPT for incorrect OTP attempt.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.14
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User is at Verify Email Screen at Wallet Creation Flow

### **Steps to Reproduce:** 
1. Tap Verify now
2. Enter incorrect OTP Code
3. Tap Verify now button
4. View Incorrect OTP Code Message

### **Expected Result:** 
Display "Incorrect OTP Code"

### **Actual Result:** 
Displaying "Incorrect OPT Code"

### **Attachment/s:** 
![Screenshot_20220314-194057](https://user-images.githubusercontent.com/100174697/158312960-ec79f54b-8535-40df-b8b9-f79d2fd2d1dc.jpg)

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.16
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
![image](https://user-images.githubusercontent.com/100174697/158509267-e5da72e9-46c1-40a1-b545-540c6f32cab3.png)

Remarks: Will transition this issue to "`Re-Open`"

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.18
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
