### ISSUE TITLE
[Account Maintenance][Email Verification] Must display additional screen for current email with "Verify Button" upon tapping "Verify your email" button at Security & Privacy.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#167]
### **Description:**
Must display additional screen for current email with "Verify Button" upon tapping "Verify your email" button at Security & Privacy.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.14
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User is at Settings Screen
3. Successfully logged in

### **Steps to Reproduce:** 
1. Tap Security & Privacy
2. Tap Verify your email button
4. View Current Email

### **Expected Result:** 
Display Current Email Screen

### **Actual Result:** 
Displaying Email Verification Screen

**Comment by johncalado** [comment]
Closing this issue as it's a deprecated requirement.
