### ISSUE TITLE
[Dashboard][Total Token] Fix must not display NaN if total Balance has long form numerical value "#########.###################".

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#170]
### **Description:**
Must not display NaN if total Balance has long form numerical value "#########.###################".

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.14
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. Successfully logged in
3. User is currently at Dashboard

### **Steps to Reproduce:** 
1. View Dashboard

### **Expected Result:** 
Display accurate Token Balance

### **Actual Result:** 
Displaying NaN

### **Attachment/s:** 
![Screenshot_20220315-050109](https://user-images.githubusercontent.com/100174697/158314169-8600eea0-90c0-478e-854d-2e4387161b8c.jpg)

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check it on the next version v1.0.7

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Re-Open`" 

Failing Criteria:
Displaying NaN KLUB for having #########.################## exact value of Tokens across all accounts in the wallet.

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.19
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
