### ISSUE TITLE
[Profile Management] Fix must remove Email Address at Edit Profile Screen. User will be able to check his current email at Security & Privacy Settings via Change Email / Verify your email.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#173]
### **Description:**
Must remove Email Address at Edit Profile Screen. User will be able to check his current email at Security & Privacy Settings via Change Email / Verify your email.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.14
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. Successfully logged in
3. User is currently at Dashboard

### **Steps to Reproduce:** 
1. Tap hamburger button
2. Tap Profile Photo
3. View Profile Information

### **Expected Result:** 
Should not display email address

### **Actual Result:** 
Displaying Email address

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/158315550-9e194be4-2f06-409d-8d63-9c0f12548a1b.mp4

**Comment by TaiTrien** [comment]
Hi @jkevincalado, if remove the email field in this screen, which screen should display email? Security & Privacy?

**Comment by jkevincalado** [comment]
That's also I'm concerned about @TaiTrien , it should be displayed upon tapping "Verify your email" and "Change Email" buttons on Settings > Security & Privacy thou currently, it's not yet included on the flow.

@salonigoel24 , if we'll be waiting for the next quarter release before we transfer the email address on their new location. I suggest to leave the email as is in Edit Profile Screen.

**Comment by salonigoel24** [comment]
@TaiTrien @jkevincalado-  keep email in edit profile, but not editable then

**Comment by jkevincalado** [comment]
Transitioning the issue to `DEFERRED`

**Comment by johncalado** [comment]
Closing this issue as it's a deprecated requirement.
