### ISSUE TITLE
[Profile Management] Fix must display Profile Photo and Phone Number after application update.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#174]
### **Description:**
Must display Profile Photo and Phone Number after application update.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.16
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Dashboard.

### **Steps to Reproduce:** 
1. Tap hamburger button
2. Tap Profile Photo
3. View Profile Information

### **Expected Result:** 
Display accurate profile information

### **Actual Result:** 
Missing Profile Photo and Phone Number (+Email)

### **Attachment/s:** 
![image](https://user-images.githubusercontent.com/100174697/158507619-8dfcd33c-058a-4648-bf65-f7315ab6bb1c.png)

**Comment by hanle9** [comment]
This issue because use wallet created in 1.0.0.15 with 1.0.0.16

**Comment by jcalado-freelancersph** [comment]
Reverification will happen on 1.0.0.17 update.

FYR: @salonigoel24

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "Re-Open" 

**Failing Criteria:**
`- Phone Number still got lost`

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
