### ISSUE TITLE
[Account Maintenance][Change Email] Fix must not display unknown wallet error message.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#175]
### **Description:**
Must not display unknown wallet error message.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.16
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Settings Screen.

### **Steps to Reproduce:** 
1. Tap Security & Privacy
2. Tap Change Email
3. Enter correct password
4. Enter new email
5. Tap Verify button

### **Expected Result:** 
Display Email Verification Screen

### **Actual Result:** 
Displaying unknown wallet error message.

### **Attachment/s:** 
![image](https://user-images.githubusercontent.com/100174697/158510950-1b575753-46a1-472d-849a-19fa07165cd5.png)

**Comment by hanle9** [comment]
This issue because use wallet created in 1.0.0.15 with 1.0.0.16

**Comment by jcalado-freelancersph** [comment]
Reverification will happen on 1.0.0.17 update.

FYR: @salonigoel24

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`PASSED`"
