### ISSUE TITLE
[Wallet Management] Fix must hide Edit Network Fee function on Send Token Confirmation Screen.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#178]
### **Description:**
Must hide Edit Network Fee function on Send Token Confirmation Screen.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User already logged in
4. User is currently on Klubcoin Dashboard.

### **Steps to Reproduce:** 
1. Tap hamburger button
2. Tap Wallet
3. Tap Send button
4. Enter recipient
5. Enter correct amount
6. View send token confirmation screen

### **Expected Result:** 
Should not have edit network fee function

### **Actual Result:** 
Displaying edit network fee function

### **Attachment/s:** 
![image](https://user-images.githubusercontent.com/100174697/158754001-8b5af3c6-6d5a-456a-aa31-fffdf044d19f.png)

**Comment by TaiTrien** [comment]
Hi @jkevincalado, please check it

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.19
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
