### ISSUE TITLE
[Klubcoin Partners] Partners Page do not display any icons and details of partners

### ISSUE THREAD

**Issue by walterbernardo23** [klubcoin/lcn-mobile#18]
**Description:**
Partners Page do not display any icons and details of partners.

**Pre requisite:**
Klubcoin app is installed on user’s device.
Build Version: 1.0.2

**Steps to Reproduce:**
1. Launch the Klubcoin App.
2. Click on "Get Started" on a welcome slider screen.
3. Click on "Check our Partners" button.

**Expected Result:**
Partners screen with the list of Klubcoin partners should be displayed.

**Actual Result:**
Partners Page do not display any icons and details of partners.

**Attachment/s:**
<img width="200" alt="Klubcoin Partners Page blank" src="https://user-images.githubusercontent.com/98941970/153324686-a128c8da-4ff0-45a7-bcbe-3ab436e4d918.png">

**Comment by TaiTrien** [comment]
Hi @salonigoel24, it's fixed in the newest version. I'll send you the new apk file

**Comment by walterbernardo23** [comment]
Fixed:
Partners screen with the list of Klubcoin partners is now displayed. Partners details are showing when user select a partner.

Please see attached:
<img width="1094" alt="18_Fixed" src="https://user-images.githubusercontent.com/98941970/154618617-d5157415-3ce8-4ba4-9517-b0a0174350b4.png">


Closing ticket.

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `Re-Open`**

**Build Environment:** Dev Environment
**Affects Version:** 1.0.0.13
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://user-images.githubusercontent.com/100174697/157792307-4e69dd98-0c20-4097-9e93-ecec84b4cd28.mp4

Remarks: Will transition this issue to "Re-Open"

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.16
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "Done" This issue is now ready to be deployed on Production
