### ISSUE TITLE
Update content and image Under Settings> Security and Privacy.(For secret recovery phrase)

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#184]
As send by Stephane on 19-03-2022,
1.update content shown Under Settings> Security and Privacy.(For secret recovery phrase) as: .piece of paper, password manager or by using one of the great recovery phrase accessories of our partner Ledger.
2. Replace video by image

![LedgerAccessories](https://user-images.githubusercontent.com/98397235/159197403-963dc559-75cf-4e54-9aeb-f2cf53e6e165.jpg)

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.19
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
