### ISSUE TITLE
[Email OTP verification]Remove Learn More link from Email Verification success screen 

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#185]
Remove Learn More link from Email Verification success screen
1. During Wallet creation
2. Under settings > verify Email
![image_2022_03_21T03_52_09_315Z](https://user-images.githubusercontent.com/98397235/159204671-fa004f9f-7520-4ed7-9106-1f9002acf0c7.png)

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.19
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
