### ISSUE TITLE
[Wallet Setup Sprint2] Password validation- Provide user with information

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#19]
**Description:**
Need an informative message what to include in the password, while setting up, and error message citing what is missing as soon as user leaves the password field.

**Pre requisite:**
Klubcoin app is installed on user’s device.
Build Version: 1.0.2

**Steps to Reproduce:**
Launch the Klubcoin App.
Click on "Get Started" on a welcome slider screen.
Enter name, surname, email and come to password setting page.
Enter a password and go to confirm password field.

**Expected Result:**
1. As user moves out of password field, put a validation and show what is missing in password. Password should include Number, an alphabet in upper case, an alphabet in lower case, and special character.

**Actual Result:**
If password is missing any one of required settings, button is not activated, but user is clueless what is wrong.

**Comment by walterbernardo23** [comment]
Password informative messages for the criteria required are displaying one by one.

For an instance, when user only type "password1", an error message "Password must have at least an alphabet in uppercase". Then user added an uppercase, the that's the only time that error message "Password must have at least a special character" will display.

**Expected:** List of criteria should be displayed.

**Actual:** Password informative messages for the criteria required are displaying one by one.

Please see attachment:
<img width="671" alt="Password validation" src="https://user-images.githubusercontent.com/98941970/153989751-754144c3-95e2-4ff8-bb97-ea39a473a9df.png">

**Comment by walterbernardo23** [comment]
Fixed:
1. There is now a list of password criteria
- a criteria will be marked check when met.
- criteria will be marked red when user leave Password field without meeting those criteria.
Please see attached:
<img width="1277" alt="19_Fixed" src="https://user-images.githubusercontent.com/98941970/154624180-1420e2db-5263-4a47-b7fa-86d453ee3445.png">


Closing ticket.
