### ISSUE TITLE
[Account Management]Updated About Klubcoin screen as per client

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#196]
**Pre-condition:**
Successfully installed the app
Successfully logged in
User is currently at drawer > settings> About Klubcoin

**Change Requested**
1. About Klubcoin page to show 2 sections
2. Section 1 has links
-- Privacy Policy - KlubCoin - Privacy _ Cookie Policy - GDPR - vGac v01 (1).doc
--Terms of Use  - KlubCoin - Terms Conditions.doc
-- Attributions-  Same as now
3. Section 2 will show social network links

![KlubCoin-About](https://user-images.githubusercontent.com/98397235/159616463-fb786a71-1fc2-4e02-ba23-abfb22944515.jpg)

**Comment by jkevincalado** [comment]
Failed Due to:

https://github.com/klubcoin/lcn-mobile/issues/204

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
