### ISSUE TITLE
[Email Verification] Fix should not reset failed attempt counter when user requested a new OTP code on Create Wallet, Verify Email via Security & Privacy Setting, and Change Email via Security & Privacy Setting Flows.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#202]
### **Description:**
Should not reset failed attempt counter when user requested a new OTP code on Create Wallet, Verify Email via Security & Privacy Setting, and Change Email via Security & Privacy Setting Flows.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.22
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User is currently at Email Verification Screen

### **Steps to Reproduce:** 
1. Enter incorrect OTP Code 5x
2. Wait for Resend Now option
3. Tap Resend Now
4. Enter incorrect OTP Code 5x
5. Wait for Resend Now option
6. Tap Resend Now
7. Enter incorrect OTP Code 6x

### **Expected Result:** 
Failed attempt counter must not be reset after requesting a new OTP Code

### **Actual Result:** 
Max Failed Attempts for Entering Incorrect OTP can be bypassed

### **Attachment/s:** 
https://drive.google.com/file/d/1uh5dVR_ixtUyq8tEPpqlotRWKrFHwAHb/view

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
