### ISSUE TITLE
[Wallet Transactions Management][Wallet Screen][Token Balance] Fix Token Balance must not be flickering and displaying 0 Balance / Actual Balance for being idled on a certain amount of time or via refreshing the screen. (approximately 2 to 5minutes interval).

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#203]
### **Description:**
Token Balance must not be flickering and displaying different values for being idled on a certain amount of time or via refreshing the screen. (approximately 2 to 5minutes interval).

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User is currently at Dashboard

### **Steps to Reproduce:** 
1. View Dashboard
2. Tap Hamburger Button
3. Tap Wallet Option
4. View Token Balance
5. Wait for around 2 to 5minutes interval
6. Check Token Balance

### **Expected Result:** 
Display accurate KLUB Token Balance

### **Actual Result:** 
Displaying 0 Token Balance after a while if User stays on Wallet Screen.

### **Attachment/s:** 
https://user-images.githubusercontent.com/100281200/161679285-f8c4bfec-b7ed-4d69-9b4b-9a0b2c780752.mp4

https://user-images.githubusercontent.com/100174697/161411571-f8e59564-b80b-402e-82a5-0acde4940216.mp4

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Re-Open`" 

**Attachment/s:**
https://user-images.githubusercontent.com/100281200/161679379-4b5f92ae-b762-40ca-ad1d-13f3be6f2118.mp4

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"

**Comment by johncalado** [comment]
Reopening this issue as it resurfaced on 1.0.0.3 PlayStore version.

**Comment by johncalado** [comment]
https://user-images.githubusercontent.com/100281200/179942463-10c092f9-6234-40f3-a657-3bcd2aaac1b2.mp4

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Production Environment
**Affects Version:** 1.0.0.production.4
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`" and closed.

@hanle9
