### ISSUE TITLE
[Account Maintenance][About][Coming Soon] Fix must not be displaying "Domain Undefined Error Message" for accessing Telegram via Coming Soon Banner and About Screen.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#204]
### **Description:**
Must not be displaying "Domain Undefined Error Message" for accessing Telegram via Coming Soon Banner and About Screen.

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User is currently at Dashboard

### **Steps to Reproduce:** 
1. View Dashboard
2. Tap Hamburger Button
3. Tap Settings
4. Tap About
5. Tap Telegram

### **Expected Result:** 
Display Telegram channel

### **Actual Result:** 
Displaying Undefined Domain Error

### **Attachment/s:** 
![Screenshot_20220402-115845](https://user-images.githubusercontent.com/100174697/161411615-f8853ec7-eaaf-4f45-af3c-6754072ce001.jpg)

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
