### ISSUE TITLE
[Wallet Account Management][Transaction History] Fix must remove Account List Access via tapping Profile Photo on Transaction History Screen.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#205]
### **Description:**
Must remove Account List Access via tapping Profile Photo on Transaction History Screen.

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User is currently at Dashboard

### **Steps to Reproduce:** 
1. View Dashboard
2. Tap Hamburger Button
3. Tap Transaction History Options
4. Tap Profile Photo

### **Expected Result:** 
Do nothing

### **Actual Result:** 
Displaying Account List

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/161411649-021d1eaf-8604-437b-a736-61f9eaf28693.mp4

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
