### ISSUE TITLE
[Wallet Transaction Management][Send Tokens] Fix must remove drop down option on Token Sender.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#206]
### **Description:**
Must remove drop down option on Token Sender.

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User is currently at Dashboard

### **Steps to Reproduce:** 
1. View Dashboard
2. Tap Hamburger Button
3. Tap Wallet
4. Tap Send
5. Tap Sender Accounts

### **Expected Result:** 
Must not have drop down option

### **Actual Result:** 
Displaying Accounts

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/161411726-244cf25c-0821-471b-889b-7cb88b194ff6.mp4

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Re-Open`" 

**Failing Criteria:**
1. Remove the drop down option on the Send Token Confirmation Screen as well. Thanks @hanle9

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
