### ISSUE TITLE
[Wallet Transaction Management][Send Tokens] Fix must remove Transfer Token to other accounts in my Wallet. 

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#207]
### **Description:**
Must remove Transfer Token to other accounts in my Wallet. 

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User is currently at Dashboard

### **Steps to Reproduce:** 
1. View Dashboard
2. Tap Hamburger Button
3. Tap Wallet
4. Tap Send
5. View Send Token Screen

### **Expected Result:** 
Must not display an option to transfer between accounts

### **Actual Result:** 
Displaying option to select an account in wallet

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/161411801-8cccc20b-d51d-4079-a977-2ec2a2800255.mp4

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
