### ISSUE TITLE
[Wallet Transaction Management][Transaction History] Fix must not have an intermittent behavior of displaying 10000000000000000000 Total Token Sent on Transaction History Details or 0 Network Fee.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#208]
### **Description:**
Must not have an intermittent behavior of displaying 10000000000000000000 Total Token Sent on Transaction History Details or 0 Network Fee.

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User is currently at Dashboard

### **Steps to Reproduce:** 
1. View Dashboard
2. Tap Hamburger Button
3. Tap Transaction History Options
4. View all transaction details

### **Expected Result:** 
Display accurate transaction details

### **Actual Result:** 
Intermittent Behavior: Displaying 10000000000 total amount sent and 0 Network Fee

### **Attachment/s:** 
![Screenshot_20220403-104706](https://user-images.githubusercontent.com/100174697/161411845-a9e4d7d0-3b59-45a7-9ff6-6f30867119bd.jpg)
![Screenshot_20220402-153844](https://user-images.githubusercontent.com/100174697/161411848-3b557472-cff4-46f5-af62-62d796d25932.jpg)

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Re-Open`" 

**Passing Criteria:**
1. Displaying accurate Token Amount

**Failing Criteria:**
1. Displaying 0 Network Fee

**Attachment/s:**
![image](https://user-images.githubusercontent.com/100281200/161681833-24b75cb2-d7d9-4b1e-a96f-4f3af53b55b8.png)

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
