### ISSUE TITLE
[Wallet Transaction Management][Send Tokens] Fix must not have an intermittent behavior of displaying JSON RPC Network Error if user sent token when Token Balance is flickering.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#209]
### **Description:**
Must not have an intermittent behavior of displaying JSON RPC Network Error if user sent token when Token Balance is flickering.

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User is currently at Dashboard

### **Steps to Reproduce:** 
1. View Dashboard
2. Tap Hamburger Button
3. Tap Wallet
4. Tap Send Option
5. Add Recipient
6. Tap Next button
7. View Token Balance
8. Enter Token Amount
9. Tap Next
10. Tap Send

### **Expected Result:** 
Successfully sent KLUB Token

### **Actual Result:** 
Intermittent Behavior: Displaying JSON RPC Network Error

### **Attachment/s:** 
![Screenshot_20220402-153634](https://user-images.githubusercontent.com/100174697/161411907-c6d212f9-746f-4440-9d22-07f8f73a5d93.jpg)

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
