### ISSUE TITLE
[Wallet Transaction Management][Send Tokens] Fix must not have an intermittent behavior of displaying 0 Token Balance and insufficient balance upon sending tokens while Token Balance is flickering.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#210]
### **Description:**
Must not have an intermittent behavior of displaying 0 Token Balance and insufficient balance upon sending tokens while Token Balance is flickering.

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. User has an existing wallet account
3. User is currently at Dashboard

### **Steps to Reproduce:** 
1. View Dashboard
2. Tap Hamburger Button
3. Tap Wallet
4. Tap Send Option
5. Add Recipient
6. Tap Next button
7. View Token Balance
8. Enter Token Amount

### **Expected Result:** 
Display accurate KLUB Token Balance and proceed to Send Token Confirmation Screen

### **Actual Result:** 
Intermittent Behavior: Displaying 0 Token Balance and insufficient balance to proceed

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/161411976-8e850c6a-b98f-4f4e-b086-d7f4bb49c43b.mp4

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"

**Comment by johncalado** [comment]
Reopening this issue as it resurfaced on 1.0.0.3 PlayStore version.

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Production Environment
**Affects Version:** 1.0.0.production.4
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`" and closed.

@hanle9
