### ISSUE TITLE
[Account Maintenance][Email Verification][Receive Email OTP Code][Onboarding ] Fix received Email OTP Code must not be displaying "Your Telecel Verification Code" instead of "Your Klubcoin Verification Code".

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#211]
### **Description:**
Received Email OTP Code must not be displaying "Your Telecel Verification Code" instead of "Your Klubcoin Verification Code".

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. User is currently on Wallet Creation Flow
2. User is currently on Verify Email via Security & Privacy Flow
3. User is currently on Change Email via Security & Privacy Flow

### **Steps to Reproduce:** 
1. Verify Email
4. Receive Email OTP Code
5. Check Email
6. View Email OTP Verification Details

### **Expected Result:** 
Display accurate Sender details "do_not_reply@klubcoin.net" and email header and content "Your Klubcoin Verification Code".

### **Actual Result:** 
Displaying "Your Telecel Verification Code"

### **Attachment/s:** 
![Screenshot_20220402-115622](https://user-images.githubusercontent.com/100174697/161412021-4e5f6059-f076-4e8c-8ab4-d4781e0fedf9.jpg)

**Comment by smichea** [comment]
fixed by modifying the setting on meveo
![image](https://user-images.githubusercontent.com/16659140/161457949-036dfc6a-e283-429e-99fd-76217761f881.png)

@johncalado  please create a ticket so that we study a way to avoid forgetting those kind of update each time we deploy a cript that use settings.

**Comment by jkevincalado** [comment]
Sure thing @smichea , btw on the otp.email.address parameter can we have its value as "do_not_reply@klubcoin.net" instead of "do_not_reply@liquichain.io"?

**Comment by jkevincalado** [comment]
### Retested and Verifying the fix as "`FAILED`"

**Attachment/s:**
![image](https://user-images.githubusercontent.com/100174697/161462180-75c86f43-5e6a-45ad-81c5-6e07c68018f2.png)
![image](https://user-images.githubusercontent.com/100174697/161462195-67f8a054-9777-4c95-86ee-f8aa14ebd3c2.png)

Still displaying "Your Telecel verification code" on Email Header, "do_not_reply@liquichain.io" as Email Sender, and "Your Telecel verification code is: 127563" on Email Body/Context.

**Comment by johncalado** [comment]
### Retested and Verifying the fix as "`FAILED`"

**Attachment/s:**
![image](https://user-images.githubusercontent.com/100281200/161676738-15e3f467-e740-4b00-978f-77bf60c273b3.png)

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

**Remarks:**
Still displaying "Your Telecel verification code" on Email Header, "do_not_reply@liquichain.io" as Email Sender, and "Your Telecel verification code is:" on Email Body/Context.

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
