### ISSUE TITLE
[Wallet Transaction Management][Token Balance] Wallet Account Token Balance is Centered on Wallet Screen when user has #########.################## Token value.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#212]
### **Description:**
Wallet Account Token Balance is Centered on Wallet Screen when user has #########.################## Token value.

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. User successfully installed the app
2. User has an existing wallet account
3. User is currently at Dashboard

### **Steps to Reproduce:** 
1. View Dashboard
2. Tap Hamburger Button
3. Tap Wallet Option
4. View Wallet Screen

### **Expected Result:** 
Display Token Balance on Left Alignment

### **Actual Result:** 
Displaying Token Balance on Center Alignment

### **Attachment/s:** 
![Screenshot_20220402-150733](https://user-images.githubusercontent.com/100174697/161412069-d206e0f1-a4ae-40aa-b06d-b11b3ec0a293.jpg)

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
