### ISSUE TITLE
[Account Maintenance][Device Sign In Settings] Fix must not be displaying [missing {{appName}} value] on device MFA through Sign in with Device PIN Setup.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#214]
### **Description:**
Must not be displaying [missing {{appName}} value] on device MFA through Sign in with Device PIN Setup.

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. User successfully installed the app
2. User has an existing wallet account
3. User is currently at Dashboard

### **Steps to Reproduce:** 
1. View Dashboard
2. Tap Hamburger Button
3. Tap Settings
4. Tap Security & Privacy
5. Tap Sign In with Device PIN
6. View Device MFA

### **Expected Result:** 
Display accurate application name and value

### **Actual Result:** 
Displaying [missing {{appName}} value] on device MFA

### **Attachment/s:** 
![275376597_1355774328167088_1278155056299136112_n](https://user-images.githubusercontent.com/100174697/161412191-8a1f0c5d-4555-4924-984a-19c489084993.jpg)

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
