### ISSUE TITLE
[Account Maintenance][Onboarding][SEED Phrase Hint] Fix must not be accepting more than 256 characters on SEED Phrase Hint Text Field cause it is breaking UI, cannot tap cancel / save button as they are truncated on the screen.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#215]
### **Description:**
Must not be accepting more than 256 characters on SEED Phrase Hint Text Field cause it is breaking UI, cannot tap cancel / save button as they are truncated on the screen.

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. User is currently on Wallet Creation Flow
2. User is currently on Back Up Again via Security & Privacy Flow

### **Steps to Reproduce:** 
1. Create Wallet
2. Setup SEED Phrase Recovery
3. Successfully Setup SEED Phrase Recovery
4. Tap Add Hint Option
5. Enter more than 256 characters on Text Box

### **Expected Result:** 
Must not accept more than 256 characters on text box

### **Actual Result:** 
Accepting more than 256 characters input and breaking UI, cannot tap cancel / save button since they are already truncated

### **Attachment/s:** 
![Screenshot_20220321-155025](https://user-images.githubusercontent.com/100174697/161412449-4515978a-56b4-4bbc-907f-1d04bbe0f228.jpg)

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.2
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
