### ISSUE TITLE
[Wallet Transaction Management][Send Tokens] Fix must have text change hint for unrecognized username, public address, ENS on send token screen.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#216]
### **Description:**
Must have text change hint for unrecognized username, public address, ENS on send token screen.

**Build Environment:** Prod Candidate Environment
**Affects Version:** 1.0.0.prod.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. User is currently on Wallet Creation Flow
2. User is currently on Back Up Again via Security & Privacy Flow

### **Steps to Reproduce:** 
1. View Dashboard
2. Tap Hamburger Button
3. Tap Wallet
4. Tap Send Option
5. Enter random input on recipient text field.

### **Expected Result:** 
Display unrecognized username, public address, ENS after text input.

### **Actual Result:** 
Displaying nothing

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/161412507-8c0711e8-5691-465a-9f91-f0b617ae3eb7.mp4

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
