### ISSUE TITLE
[Import Using Secret Recovery Phrase] User unable to login after successful import of secret recovery phrase. (By typing the actual secret recovery phrase)

### ISSUE THREAD

**Issue by walterbernardo23** [klubcoin/lcn-mobile#22]
**Description:**
User unable to login after successful import of secret recovery phrase. (By typing the actual secret recovery phrase)

**Pre requisite:**
Klubcoin app is installed on user’s device
User has successfully imported wallet using secret recovery phrase. (By typing the actual secret recovery phrase)

**Steps to Reproduce:**
1. On the dashboard, click Options (3 lines) icon on the upper left of the screen.
2. Select Logout and Click Yes.
3. On the Login Page, populate correct email and password.
4. Click Log in button.

**Expected Result:**
User should be able to login successfully.

**Actual Result:**
User unable to login after successful import of secret recovery phrase.

**Attachment/s:**
<img width="1155" alt="Unable to login - type rcp" src="https://user-images.githubusercontent.com/98941970/153339145-3cce3a76-a763-451c-be87-ee4f41faeafe.png">

**Comment by johncalado-manaty** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Development Environment
**Affects Version:** 1.0.0.8
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://user-images.githubusercontent.com/100281200/155453663-e8b8819a-c574-45e0-b8c1-42b7a8198d8f.mp4

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Development Environment
**Affects Version:** 1.0.0.8
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://user-images.githubusercontent.com/100281200/155453663-e8b8819a-c574-45e0-b8c1-42b7a8198d8f.mp4

Remarks: Will transition this issue to "Re-Open"

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "Done"
