### ISSUE TITLE
[Wallet Setup Sprint2] Email Address is unique a wallet.

### ISSUE THREAD

**Issue by walterbernardo23** [klubcoin/lcn-mobile#23]
**Description:**
New wallet cannot be created on an email address linked with some other wallet. User sees validation message about existing wallet on that email address.

**Pre requisite:**
User has clicked Create a New Wallet button.
Build Version: 1.0.2

**Steps to Reproduce:**
1. On Profile screen, input an email address which is already linked to other wallet.
2. Input valid phone number
3. Click Continue.

**Expected Result:**
Error message about existing wallet on that email address should be displayed.

**Actual Result:**
Right now the email is just public info not an identifier

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://github.com/klubcoin/lcn-mobile/issues/66

Remarks: Will transition this issue to "Done"
