### ISSUE TITLE
[Wallet Setup Sprint2] Setup wallet using an existing username should not be allowed

### ISSUE THREAD

**Issue by walterbernardo23** [klubcoin/lcn-mobile#25]
**Description:**
Username for a wallet should be unique and cannot be used for creating other wallet.

**Pre requisite:**
1. User has completed setting Profile.
2. User is at Create Password screen.
Build Version: 1.0.2

**Steps to Reproduce:**
1. On Username field, input an existing username.

**Expected Result:**
Error message about username being already used on other wallet should be displayed.

**Actual Result:**
Username right now is not unique.

**Comment by salonigoel24** [comment]
@TaiTrien On typing a username already taken, user should see a message- "Username Taken. Try another."

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED with Trivial Defect`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://github.com/klubcoin/lcn-mobile/issues/71

Remarks: Will transition this issue to "Done"
