### ISSUE TITLE
[Account Maintenance][Change email]Show blocked email warning when trying to change to blocked email

### ISSUE THREAD

**Issue by hanle9** [klubcoin/lcn-mobile#258]
### **Description:**
Show blocked email warning when trying to change to blocked email.

**Build Environment:** Staging Candidate Environment
**Affects Version:** 
**Device Platform:** Android
**Device OS:** Android 12
**Test Device:** Samsung S21

### **Pre-condition:**
1. User successfully installed Klubcoin App
2. User has an existing Klubcoin Wallet Account
3. Changing email has been blocked
4. User email has not been verified
5. User is currently at Klubcoin Dashboard

### **Steps to Reproduce:** 
1. Tap Hamburger Button
2. Tap Settings
3. Tap Security & Privacy
4. Tap Verify your email
5. Enter the password
6. Enter blocked email
7. Tap Verify

### **Expected Result:** 
The app show blocked email warning.

### **Actual Result:** 
Nothing.

### **Attachment/s:**

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Staging Environment
**Fix Version:** 1.0.staging.27
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to **`Reopen`**

Kindly change where to trigger blocked email verification message prompt.
**Steps:**
1. Tap Hamburger Button
2. Tap Settings
3. Tap Security & Privacy
4. Tap Change Email
5. Display Blocked Email Verification Prompt Message

cc; @hanle9

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.staging.28
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Closed`"
