### ISSUE TITLE
[Klubcoin Partners Sprint2] Partners Page do not display any icons and details of partners 

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#27]
**Description:**
Partners List Page should display list in alphabetical order

Pre requisite:
Klubcoin app is installed on user’s device.
Build Version: 1.0.2

Steps to Reproduce:

Launch the Klubcoin App.
Click on "Get Started" on a welcome slider screen.
Click on "Check our Partners" button.

**Expected Result:**
Partners screen with the list of Klubcoin partners should be displayed in  alphabetical order

**Actual Result:**
Partners list is not sorted alphabetically

**Comment by walterbernardo23** [comment]
Partners list is now showing in alphabetical order of Partners. User can click on each partners to see details.

Please see attached:
<img width="1094" alt="27_Fixed" src="https://user-images.githubusercontent.com/98941970/154616575-20ff4815-ddac-4d7b-a458-8df9738b1860.png">


Closing ticket.
