### ISSUE TITLE
[Wallet Setup Sprint2] Phone number field: There should be a inline message or warning message that the user has to select country code first

### ISSUE THREAD

**Issue by walterbernardo23** [klubcoin/lcn-mobile#30]
**Description:**
1. There should be a inline message AND warning message that the user has to select country code first and separate fields for country code "+" sign and the 10 digit number.

**Pre requisite:**
1. Klubcoin app is installed on user’s device
2. User has clicked Create a New Wallet button.
Build Version: 1.0.0

**Steps to Reproduce:**
1. On Profile screen, click on phone number field.

**Expected Result:**
1. There should be a inline message telling user to click on + sig to select country code first.
- Need a warning message if user clicks on phone number test area, without selecting country code.
- User must not be allowed to input 10 digit number if no country code selected.
2. There should be separate fields for country code "+" sign and the 10 digit number. Here is an example:
![image](https://user-images.githubusercontent.com/98941970/154193290-fc6c5273-52f0-455a-ac9a-a7a89c388b07.png)

**Actual Result:**
1.  There should be a inline message or warning message on the Phone number field that the user has to click "+" sign and select country code first.
2. No separation

**Comment by salonigoel24** [comment]
@hanle9 can you have the country code pre selected depending on the phone location?

**Comment by walterbernardo23** [comment]
1. A warning message is now displayed when user clicks on phone number test area without selecting country code.
2. User must not be allowed to input 10 digit number if no country code selected.
3. Country code and 10 digit phone number fields are now separated.

Please see below:
<img width="425" alt="30_Fixed" src="https://user-images.githubusercontent.com/98941970/154613572-c6eed14d-2e74-4107-bf5c-6d623f97793d.png">

**Comment by salonigoel24** [comment]
> @hanle9 can you have the country code pre selected depending on the phone location?

we are good with current implementation of country code field showing dropdown, no need to implement default country code
