### ISSUE TITLE
[Wallet Setup] Create Password Screen - Remember me toggle switch is on the right side

### ISSUE THREAD

**Issue by walterbernardo23** [klubcoin/lcn-mobile#32]
**Description:**
Remember me toggle switch is on the right side.

**Pre requisite:**
Klubcoin app is installed on user’s device
User has clicked Create a New Wallet button.
User has completed setting Profile.
Build Version: 1.0.0

**Steps to Reproduce:**
1. On Create Password screen, check the Remember me toggle switch.

**Expected Result:**
1. Remember me toggle switch. should be on the left side based on prototype.

**Actual Result:**
1. Remember me toggle switch is on the right side.

**Attachment/s:**
<img width="197" alt="Remember me toggle switch is on the right side" src="https://user-images.githubusercontent.com/98941970/154198757-2c68a982-9d8b-4a9c-b853-380b1d61d2d3.png">

**Comment by salonigoel24** [comment]
THis implementation is good. Closing the ticket
![image](https://user-images.githubusercontent.com/98397235/154636522-7d8e4475-5f9d-4497-90b4-50f62e9afd46.png)
