### ISSUE TITLE
[Wallet Setup Sprint2] Create Wallet Screen - Name, Surname, Username should not allow emojis

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#33]
**Description:**
Create Wallet Screen - Name, Surname, Username should not allow emojis

**Pre requisite:**
Klubcoin app is installed on user’s device
User has clicked Create a New Wallet button.
Build Version: 1.0.0

**Steps to Reproduce:**
Create Wallet Screen -click on Name, Surname, Username should not allow emojis

**Expected Result:**
Name, Surname, Username should not allow emojis

**Actual Result:**
Emojis can be entere
![Emojis](https://user-images.githubusercontent.com/98397235/154633086-a6bbbe1a-cd5b-474f-b270-eb8163477677.JPEG)
d

**Comment by walterbernardo23** [comment]
**Fixed:**
Name, Surname, Username fields are not allowing emojis.

Please see attached:

https://user-images.githubusercontent.com/98941970/154680102-56a3809e-121b-4988-bc12-85ac9746912a.mp4

https://user-images.githubusercontent.com/98941970/154680132-5bd094d0-c371-4bb1-a413-0859726171ac.mp4



Closing ticket.
