### ISSUE TITLE
[View on Klubcoin] User is not redirected to Klubcoin website after clicking View on Klubcoin option

### ISSUE THREAD

**Issue by walterbernardo23** [klubcoin/lcn-mobile#35]
**Description:**
User is not redirecting to Klubcoin website after clicking View on Klubcoin option.

**Pre-requisite:**
1. User is logged in on Klubcoin app.
Build Version: 1.0.0

**Steps to Reproduce:**
1. Click on the hamburger button to open the drawer.
2. On the drawer, select View on Klubcoin option.

**Expected Result:**
User should be redirected to Klubcoin website after clicking View on Klubcoin option.

**Actual Result:**
User is not redirecting to Klubcoin website after clicking View on Klubcoin option.

**Please see attachment:**
<img width="567" alt="View on Klubcoin" src="https://user-images.githubusercontent.com/98941970/154889405-f2d0f606-73d8-48d0-bac5-adf4aa1933a6.png">

**Comment by johncalado-manaty** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Development Environment
**Affects Version:** 1.0.0.8
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://user-images.githubusercontent.com/100281200/155454691-6f576e4c-9fc2-4a3b-988c-0037877aa8b2.mp4

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Development Environment
**Fix Version:** 1.0.0.8
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://user-images.githubusercontent.com/100281200/155454691-6f576e4c-9fc2-4a3b-988c-0037877aa8b2.mp4
