### ISSUE TITLE
[FAQ] Don't show empty list 

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#36]
**Description:**
User is shown an empty list contents after 3 FAQs with Arrows, which redirect to empty pages.

**Pre-requisite:**
User is logged in on Klubcoin app.
Build Version: 1.0.0

**Steps to Reproduce:**
Click on the hamburger button to open the drawer.
On the drawer, select FAQs.
FAQ list has just 3 questions, but shows emty list under it.
Empty list has has with Arrows, which redirect to empty pages.

**Expected Result:**
User should be shown list correctly populated with FAQs. NO empty list

Actual Result:
![FAQ page](https://user-images.githubusercontent.com/98397235/154959938-ed3679d6-e59e-4aba-bdee-6a7a1a1bd536.jpg)

User is shown empty list contents after 3 FAQ items. Clicking on arrow redirects to empty page

**Comment by johncalado-manaty** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Development Environment
**Affects Version:** `1.0.0.8`
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://user-images.githubusercontent.com/100281200/155455156-8b8a1158-c993-49b7-b5b2-7240d6b4b055.mp4

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Development Environment
**Affects Version:** `1.0.0.8`
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://user-images.githubusercontent.com/100281200/155455156-8b8a1158-c993-49b7-b5b2-7240d6b4b055.mp4

### **Remarks**
Will transition this issue to `Re-Open`

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
![Screenshot_20220308-103349](https://user-images.githubusercontent.com/100174697/157158689-b3e1b866-1250-4667-a867-fdaec6ef2333.jpg)


Remarks: Will transition this issue to "Done"

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `Re-Open`**

**Build Environment:** Dev Environment
**Affects Version:** 1.0.0.13
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
![Screenshot_20220310-230952](https://user-images.githubusercontent.com/100174697/157792405-0832059f-012e-4e77-9410-499f572fce0e.jpg)

Remarks: Will transition this issue to "Re-Open"

**Comment by TaiTrien** [comment]
Hi @salonigoel24 and @jcalado-freelancersph, please check on next release

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.15
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "Done" This issue is now ready to be deployed on Production
