### ISSUE TITLE
[Onboarding] Fix should not display LiquiChain's splash screen upon launching klubcoin app.

### ISSUE THREAD

**Issue by jcalado-freelancersph** [klubcoin/lcn-mobile#59]
### **Description:**
Should not display LiquiChain's splash screen upon launching klubcoin app.

**Build Environment:** Development Environment
**Affects Version:** 1.0.0.8
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Klubcoin app is already installed on user's device.

### **Steps to Reproduce:** 
1. Tap the Klubcoin Application on device

### **Expected Result:** 
1. Display klubcoin's splash screen
2. Application should be launched successfully
3. Redirect to klubcoin welcome screen after splash screen.

### **Actual Result:** 
Displaying LiquiChain's Splash Screen before klubcoin's Splash Screen

### **Attachment/s:** 
![image](https://user-images.githubusercontent.com/100174697/155490106-7dbb68e7-4180-4faa-8ae3-d3a7fa27e4bb.png)

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please check on next dev version (v.1.0.0+14(dev))

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.14
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "Done"

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.15
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`RE-OPEN`"

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.16
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`DONE`" . This issue is now ready to be deployed on Production.
