### ISSUE TITLE
[Onboarding][Wallet Creation] Fix should not accept leading and trailing space email format as well as symbol character on domain address.

### ISSUE THREAD

**Issue by jcalado-freelancersph** [klubcoin/lcn-mobile#65]
### **Description:**
Should not accept leading and trailing space email format.

**Build Environment:** Development Environment
**Affects Version:** 1.0.0.8
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. User is already on wallet creation setup profile screen.
2. User already attached a profile photo

### **Steps to Reproduce:** 
1. Input name
2. Input surname
3. Input invalid email address
4. Input valid phone number.
5. Click Continue button.

### **Expected Result:** 
Display invalid email format message

### **Actual Result:** 
Accepting leading and trailing space email format. Test Data that failed the test are "test1@em1.a/il.co", " test@domain.com", and "test@domain.com "

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/155925364-19011139-947b-4c8e-ae8b-2cf6ace26213.mp4

**Comment by jcalado-freelancersph** [comment]
### Current behavior in Dev Environment 1.0.0.13:

- Frontend validation for email format is different from backend. Frontend validation accepts `test1@em1.a/il.com` as valid format. 
- There's no inline message/hint pertaining to user that the email address format is incorrect.
- Continue button is enabled for entering invalid email address format.

**Please see screenshot below:**
![image](https://user-images.githubusercontent.com/100174697/157806185-489a341d-66b2-491a-8411-2cfd63beae54.png)

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please check on next version (v.1.0.0+14(dev))

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.15
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "Done" This issue is now ready to be deployed on Production
