### ISSUE TITLE
[Onboarding][Wallet Creation] Fix should not accept used email address on wallet account creation.

### ISSUE THREAD

**Issue by jcalado-freelancersph** [klubcoin/lcn-mobile#66]
### **Description:**
Should not accept used email address on wallet account creation.

**Build Environment:** Development Environment
**Affects Version:** 1.0.0.8
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. User is already on wallet creation setup profile screen.
2. User already attached a profile photo

### **Steps to Reproduce:** 
1. Input name
2. Input surname
3. Input used email address
4. Input valid phone number.
5. Click Continue button.

### **Expected Result:** 
Display email address already used message
Should let user know email is already used after leaving email textbox not after setting up the password.

### **Actual Result:** 
Accepting used email address

### **Attachment/s:** 
![Screenshot_20220228-122201](https://user-images.githubusercontent.com/100174697/155926262-fc038ffc-aeac-4891-a68f-4c8261939617.jpg)

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Dev Environment
**Affects Version:** 1.0.0.13
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
![Screenshot_20220310-223826](https://user-images.githubusercontent.com/100174697/157792544-dbb63748-9ce0-420b-8ff8-b3c6c61e03c5.jpg)

Remarks: Will transition this issue to "QA Done". **This issue is now ready to be deployed to Staging Environment.**

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please have a check and close this ticket

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.15
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "Done" This issue is now ready to be deployed on Production
