### ISSUE TITLE
[Wallet Management][Add Account] Fix should not display stack trace errors on mobile app due to Fetching Account List Data Primary ID issue.

### ISSUE THREAD

**Issue by jcalado-freelancersph** [klubcoin/lcn-mobile#67]
### **Description:**
Should not display stack trace errors on mobile app due to Fetching Account List Data Primary ID issue.

**Build Environment:** Development Environment
**Affects Version:** 1.0.0.8
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. User is already on Klubcoin Dashboard
2. User already logged in

### **Steps to Reproduce:** 
1. Tap Hamburger button
2. View drawer options
3. Tap account name
4. Tap import an account button
5. Tap Scan a QR Code
6. Scan a valid QR Code
7. Tap Create Account button
8. Long press an account
9. Delete an account
10. Long press another account
11. Delete an account
12. Tap create new account
13. Tap Import an account button
14. Input private key
15. Tap Import button
16. View Stack Trace Error Report

### **Expected Result:** 
Application should not be displaying stack trace errors on data fetching errors.

### **Actual Result:** 
Displayed stack trace logs and details which might cause vulnerability issue.

### **Attachment/s:** 
![Screenshot_20220227-134530](https://user-images.githubusercontent.com/100174697/155870419-370c5521-98cf-4894-9e98-974d351c896f.jpg)
![Screenshot_20220227-134917](https://user-images.githubusercontent.com/100174697/155870424-fc37d434-6af7-4589-a327-7ec8bb43c8fa.jpg)
![Screenshot_20220227-134958](https://user-images.githubusercontent.com/100174697/155870425-593ce33c-241e-4192-9f43-f5ff4db274f4.jpg)

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please check on next version (v.1.0.0+14(dev))

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.14
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`" This issue is now ready to be deployed on Production.
