### ISSUE TITLE
[Onboarding][Wallet Creation] Fix should not accept small initial letter case for name on wallet account creation.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#68]
### **Description:**
Should not accept small initial letter case for name on wallet account creation.

**Build Environment:** Development Environment
**Affects Version:** 1.0.0.8
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. User is already on wallet creation setup profile screen.

### **Steps to Reproduce:** 
1. Attach profile photo
2. Input small initial letter on name
3. Input surname
4. Input valid email address
5. Input valid phone number.
6. Click Continue button.

### **Expected Result:** 
Display name should start with capital letter message

### **Actual Result:** 
Accepting small case letters on name

### **Attachment/s:** 
![Screenshot_20220228-122201](https://user-images.githubusercontent.com/100174697/155926235-43ddf8fd-d4e5-434e-a62f-2e7e397ae087.jpg)

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please check on next version (v.1.0.0+14(dev))

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.16
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Re-Open`"

**Comment by jkevincalado** [comment]
Will close this issue as discussed with @salonigoel24 and @hanle9 to leave the name and surname field optional whether to use uppercase or lowercase initial letter.

FYR: @TaiTrien
