### ISSUE TITLE
[Onboarding][Wallet Creation] Add message that username is required every time user leaves the username textbox on wallet account creation.

### ISSUE THREAD

**Issue by jcalado-freelancersph** [klubcoin/lcn-mobile#70]
### **Description:**
Add message that username is required every time user leaves the username textbox on wallet account creation.

**Build Environment:** Development Environment
**Affects Version:** 1.0.0.8
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. User is already on wallet account creation setup password screen

### **Steps to Reproduce:** 
1. Input valid password format
2. Input matching password
3. Input empty username
4. Tick checkbox for password recovery terms and conditions
5. Tap Create Password

### **Expected Result:** 
1. Display username is required
2. Create Password button disabled

### **Actual Result:** 
No hints or messages displayed for leaving username empty

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/155925217-f1747fc6-c23b-4169-b2c9-91ea663f0d25.mp4

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Dev Environment
**Affects Version:** 1.0.0.13
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://user-images.githubusercontent.com/100174697/157798573-f89fd83e-302b-46a8-b8d7-fa8374ae9990.mp4

Remarks: Will transition this issue to "Re-Open"

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please check. on next version (v.1.0.0+14(dev))
