### ISSUE TITLE
[Onboarding][Wallet Creation] Fix should not accept used username on wallet account creation.

### ISSUE THREAD

**Issue by jcalado-freelancersph** [klubcoin/lcn-mobile#71]
### **Description:**
Should not accept used username on wallet account creation.

**Build Environment:** Development Environment
**Affects Version:** 1.0.0.8
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. User is already on wallet account creation setup password screen

### **Steps to Reproduce:** 
1. Input valid password format
2. Input matching password
3. Input used username
4. Tick checkbox for password recovery terms and conditions
5. Tap Create Password

### **Expected Result:** 
Should let user know username is already used after leaving username textbox not after setting up the password.

### **Actual Result:** 
Accepting used username

### **Attachment/s:** 
![Screenshot_20220228-122519](https://user-images.githubusercontent.com/100174697/155926310-bd4c0e5b-dd1b-45a6-9317-a7bfd320bd0c.jpg)

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Dev Environment
**Affects Version:** 1.0.0.13
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
![Screenshot_20220310-223421__01](https://user-images.githubusercontent.com/100174697/157792110-067998c3-b1c4-475a-9a31-4b2c38ef1377.jpg)

Remarks: Will transition this issue to "Re-Open"

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please check on next version (v.1.0.0+14(dev))

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.15
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "Done" This issue is now ready to be deployed on Production.
