### ISSUE TITLE
[Coming Soon screen] Add this screen

### ISSUE THREAD

**Issue by salonigoel24** [klubcoin/lcn-mobile#81]
Add this screen to all coming soon features.

Coming soon features : -
1 Chat (drawer)
2. View on klubcoin
3. Collect (drawer)
4.Trade (wallet)
5.Dashboard graphs. 

![KlubCoin-Phone_Coming_Soon_v2](https://user-images.githubusercontent.com/98397235/156095763-4b21a804-7f1f-4ae7-8b84-12eb45cb583d.jpg)

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Development Environment
**Fix Version:** 1.0.0.9
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://drive.google.com/file/d/199D58zXRQNwM4kLIim6ZwduleGkXI14g/view

### **Remarks**
Will transition this issue now to `Done`

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `FAILED`**

**Build Environment:** Dev Environment
**Affects Version:** 1.0.0.13
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
![Screenshot_20220310-230524](https://user-images.githubusercontent.com/100174697/157792982-49bf39e9-7433-4599-876e-a2841a76fee4.jpg)

Remarks: Will transition this issue to "Re-Open".

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please check on next version (v.1.0.0+14(dev))

**Comment by jcalado-freelancersph** [comment]
Apply "Coming Soon" Banner on the following as well:

- Tips
- Manage my Coins
- Metamask SEED Phrase Help Video

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`PASSED`"
