### ISSUE TITLE
[Profile Management][Update Profile] Fix should not display unknown wallet error message upon tapping update profile button.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#84]
### **Description:**
Should not display unknown wallet error message upon tapping update profile button.

**Build Environment:** Development Environment
**Affects Version:** 1.0.0.8
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Klubcoin app is installed on user’s device.
2. User already successfully created a wallet account.
3. User is currently on klubcoin Dashboard.
4. User has added a new account via "Create New Account / Import Account"
5. User is currently using Added/Imported Account (Account 1, Account 2, Account 3, and so on usernames)

### **Steps to Reproduce:** 
1. Tap Hamburger button
2. Tap Profile Photo
3. Tap Update Profile button

### **Expected Result:** 
Must display accurate profile information

### **Actual Result:** 
Displaying unknown wallet error message.

### **Attachment/s:** 
![image](https://user-images.githubusercontent.com/100174697/156129415-68c81dda-3a9b-413e-92b8-2e4ea202980b.png)

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://user-images.githubusercontent.com/100174697/157160554-ab758c26-bdf0-4998-89de-19c4d7a35df0.mp4

Remarks: Will transition this issue to "Done"

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `REOPEN`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.16
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
![image](https://user-images.githubusercontent.com/100174697/158510039-504c3fbe-ab24-40ab-b48f-ebca2739c736.png)

Remarks: Will transition this issue to "`Re-Open`"

**Comment by hanle9** [comment]
This issue because use wallet created in 1.0.0.15 with 1.0.0.16

**Comment by jcalado-freelancersph** [comment]
Reverification will happen on 1.0.0.17 update.

FYR: @salonigoel24

**Comment by jkevincalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.17
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`PASSED`"

**Comment by jkevincalado** [comment]
Transitioning this issue as `Closed` as Wallet Account Management is not needed on Business Requirements and must be removed on the Application which resolves the issue on displaying Unknown Wallet Error when User Updates Profile while using an Imported / Added Account.
