### ISSUE TITLE
[Onboarding][Wallet Creation] Fix must be able to proceed to secure wallet flow after setting up password.

### ISSUE THREAD

**Issue by jcalado-freelancersph** [klubcoin/lcn-mobile#91]
### **Description:**
Must be able to proceed to secure wallet flow after setting up password and username.

**Build Environment:** Development Environment
**Affects Version:** 1.0.0.9
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Successfully installed the app
2. Launched the app successfully

### **Steps to Reproduce:** 
1. Input valid password format
2. Input matching password
3. Input valid username
4. Tick checkbox for password recovery terms and conditions
5. Tap Create Password

### **Expected Result:** 
Display secure wallet screen.

### **Actual Result:** 
Displaying something went wrong error message.

### **Attachment/s:** 
https://user-images.githubusercontent.com/100174697/156486393-ea91f4e7-7027-4b13-9a9f-6538f4aae32a.mp4

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://user-images.githubusercontent.com/100174697/157157210-14fa7900-ae41-4979-bcbc-0db028f24743.mp4

Remarks: Will transition this issue to "Done"

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `REOPENED`**

**Build Environment:** Dev Environment
**Affects Version:** 1.0.0.13
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Test Evidence**
https://user-images.githubusercontent.com/100174697/157795104-a57ef190-4171-4c0f-a04a-0507d0aff105.mp4

Remarks: Will transition this issue to "Re-Open" `DO NOT DEPLOY THE CHANGES MADE IN WALLET CREATION TO STAGING UNTIL UNDERLYING CAUSE WAS DETERMINED AND SOLVED.`

**Comment by TaiTrien** [comment]
Hi @jcalado-freelancersph, please check on next version (v.1.0.0+14(dev))

**Comment by jcalado-freelancersph** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.16
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`DONE`" This issue is now ready to be deployed to Production.
