### ISSUE TITLE
[Onboarding][Wallet Creation][Authentication] Display "Network error!" as error message header and "No internet connection. Please try again." for error message description.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#93]
### **Scope:**
1. Create a Wallet on Wallet Setup Screen
2. Import using Secret Recovery Phrase on Wallet Setup Screen
3. Check our Partners on Wallet Setup Screen
4. Sync with Klubcoin Extensions on Wallet Setup Screen
5. Login on Login Screen

**Build Environment:** Development Environment
**Affects Version:** `1.0.0.9`

### **Please refer to attachment/s below:** 
![Screenshot_20220303-142635](https://user-images.githubusercontent.com/100174697/156528572-ab8946ee-5b1d-4570-a88a-12b16ee89c57.jpg)

**Comment by johncalado** [comment]
### **Retested and verifying this issue as `PASSED`**

**Build Environment:** Prod Environment
**Affects Version:** 1.0.0.production.1
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

Remarks: Will transition this issue to "`Done`"
