### ISSUE TITLE
[Profile Management][Imported Wallet] Fix should display profile photo of imported wallet.

### ISSUE THREAD

**Issue by jkevincalado** [klubcoin/lcn-mobile#96]
### **Description:**
Should display profile photo of imported wallet.

**Build Environment:** Staging Environment
**Affects Version:** 1.0.0.12
**Device Platform:** Android
**Device OS:** 11
**Test Device:** OnePlus 7T Pro

### **Pre-condition:**
1. Klubcoin app is installed on user’s device.
2. User already successfully created a wallet account.
3. User is currently on klubcoin Dashboard.

### **Steps to Reproduce:** 
1. Tap Hamburger button
2. View drawer options
3. Tap photo thumbnail / gear icon
4. View account details

### **Expected Result:** 
Display account profile details accurately for imported wallet.

### **Actual Result:** 
Profile Photo displaying empty value for imported wallet.

### **Attachment/s:** 
![Screenshot_20220308-104244](https://user-images.githubusercontent.com/100174697/157159851-796104bc-cf05-4d34-a377-51974eb7600e.jpg)
![Screenshot_20220310-230636](https://user-images.githubusercontent.com/100174697/157791123-eff15df3-27c6-411d-8471-fd0fa1bd573a.jpg)

**Comment by hanle9** [comment]
@jcalado-freelancersph Wallet photo not send to server. It just stored in local. So can't restore profile photo of wallet

**Comment by salonigoel24** [comment]
@TaiTrien @hanle9 @johncalado  Deffering this Ticket for now. Will pick as enhancement in Q2

**Comment by johncalado** [comment]
Closing this issue as per client Profile Photo won't be required on Wallet Creation and Update Profile Flow.
